INSERT INTO
    regioni (nomeRegione)
VALUES
    ('Abruzzo'),
    ('Basilicata'),
    ('Calabria'),
    ('Campania'),
    ('Emilia-Romagna'),
    ('Friuli-Venezia Giulia'),
    ('Lazio'),
    ('Liguria'),
    ('Lombardia'),
    ('Marche'),
    ('Molise'),
    ('Piemonte'),
    ('Puglia'),
    ('Sardegna'),
    ('Sicilia'),
    ('Toscana'),
    ('Trentino-Alto Adige'),
    ('Umbria'),
    ('Valle d\'Aosta'),
    ('Veneto');

INSERT INTO province (nomeProvincia, sigla, id_regione) VALUES
    ('Chieti', 'CH', 1),
    ('L\'Aquila', 'AQ', 1),
    ('Pescara', 'PE', 1),
    ('Teramo', 'TE', 1),
    ('Matera', 'MT', 2),
    ('Potenza', 'PZ', 2),
    ('Catanzaro', 'CZ', 3),
    ('Cosenza', 'CS', 3),
    ('Crotone', 'KR', 3),
    ('Reggio Calabria', 'RC', 3),
    ('Vibo Valentia', 'VV', 3),
    ('Avellino', 'AV', 4),
    ('Benevento', 'BN', 4),
    ('Caserta', 'CE', 4),
    ('Napoli', 'NA', 4),
    ('Salerno', 'SA', 4),
    ('Bologna', 'BO', 5),
    ('Ferrara', 'FE', 5),
    ('Forlì-Cesena', 'FC', 5),
    ('Modena', 'MO', 5),
    ('Parma', 'PR', 5),
    ('Piacenza', 'PC', 5),
    ('Ravenna', 'RA', 5),
    ('Reggio Emilia', 'RE', 5),
    ('Rimini', 'RN', 5),
    ('Gorizia', 'GO', 6),
    ('Pordenone', 'PN', 6),
    ('Trieste', 'TS', 6),
    ('Udine', 'UD', 6),
    ('Frosinone', 'FR', 7),
    ('Latina', 'LT', 7),
    ('Rieti', 'RI', 7),
    ('Roma', 'RM', 7),
    ('Viterbo', 'VT', 7),
    ('Genova', 'GE', 8),
    ('Imperia', 'IM', 8),
    ('La Spezia', 'SP', 8),
    ('Savona', 'SV', 8),
    ('Bergamo', 'BG', 9),
    ('Brescia', 'BS', 9),
    ('Como', 'CO', 9),
    ('Cremona', 'CR', 9),
    ('Lecco', 'LC', 9),
    ('Lodi', 'LO', 9),
    ('Mantova', 'MN', 9),
    ('Milano', 'MI', 9),
    ('Monza e della Brianza', 'MB', 9),
    ('Pavia', 'PV', 9),
    ('Sondrio', 'SO', 9),
    ('Varese', 'VA', 9),
    ('Ancona', 'AN', 10),
    ('Ascoli Piceno', 'AP', 10),
    ('Fermo', 'FM', 10),
    ('Macerata', 'MC', 10),
    ('Pesaro e Urbino', 'PU', 10),
    ('Campobasso', 'CB', 11),
    ('Isernia', 'IS', 11),
    ('Alessandria', 'AL', 12),
    ('Asti', 'AT', 12),
    ('Biella', 'BI', 12),
    ('Cuneo', 'CN', 12),
    ('Novara', 'NO', 12),
    ('Torino', 'TO', 12),
    ('Verbano-Cusio-Ossola', 'VB', 12),
    ('Vercelli', 'VC', 12),
    ('Bari', 'BA', 13),
    ('Barletta-Andria-Trani', 'BT', 13),
    ('Brindisi', 'BR', 13),
    ('Foggia', 'FG', 13),
    ('Lecce', 'LE', 13),
    ('Taranto', 'TA', 13),
    ('Cagliari', 'CA', 14),
    ('Carbonia-Iglesias', 'CI', 14),
    ('Medio Campidano', 'VS', 14),
    ('Nuoro', 'NU', 14),
    ('Ogliastra', 'OG', 14),
    ('Olbia-Tempio', 'OT', 14),
    ('Oristano', 'OR', 14),
    ('Sassari', 'SS', 14),
    ('Sud Sardegna', 'SU', 14),
    ('Agrigento', 'AG', 15),
    ('Caltanissetta', 'CL', 15),
    ('Catania', 'CT', 15),
    ('Enna', 'EN', 15),
    ('Messina', 'ME', 15),
    ('Palermo', 'PA', 15),
    ('Ragusa', 'RG', 15),
    ('Siracusa', 'SR', 15),
    ('Trapani', 'TP', 15),
    ('Arezzo', 'AR', 16),
    ('Firenze', 'FI', 16),
    ('Grosseto', 'GR', 16),
    ('Livorno', 'LI', 16),
    ('Lucca', 'LU', 16),
    ('Massa-Carrara', 'MS', 16),
    ('Pisa', 'PI', 16),
    ('Pistoia', 'PT', 16),
    ('Prato', 'PO', 16),
    ('Siena', 'SI', 16),
    ('Bolzano', 'BZ', 17),
    ('Trento', 'TN', 17),
    ('Perugia', 'PG', 18),
    ('Terni', 'TR', 18),
    ('Aosta', 'AO', 19),
    ('Belluno', 'BL', 20),
    ('Padova', 'PD', 20),
    ('Rovigo', 'RO', 20),
    ('Treviso', 'TV', 20),
    ('Venezia', 'VE', 20),
    ('Verona', 'VR', 20),
    ('Vicenza', 'VI', 20);


